---
title: "final_project"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(lavaan)
library(semTools)
library(tidyverse)
library(here)
library(rio)
library(janitor)
library(stringr)
library(knitr)
library(broom)
library(lmSupport)
library(olsrr)
library(psych)
library(car)
library(stats)
library(viridis)
library(heatmaply)
options("scipen" = 999)
```

# import and prep data
```{r import_data, include=FALSE}
# import covid_data
covid_data <-  import(here("data", "synth_covid_data.csv"))
```

```{r prep_country_data, include=FALSE}
# countries by name, not number
countries_in_order = c("Australia","Argentina","Mexico","India","Nigeria","Egypt","China","Saudi Arabia","USA")

covid_data = covid_data %>%
  mutate(country_of_residence = factor(country_of_residence, 
                                       levels = c(1:9),
                                       labels = countries_in_order))
```

```{r measure_scores, include=FALSE}
# make column for perceived controlability score
covid_data = covid_data %>%
  select(m_turk_code, contains("perceived_control")) %>%
  gather(item, value, -m_turk_code) %>%
  #this is a learning point for me - I haven't seen gather() applied in this way. I think I know what it's doing... but I'll look at the documentation some more to solidify my own learning here.
  group_by(m_turk_code) %>%
  summarize(control = mean(value)) %>%
  full_join(covid_data)

# make column for government preparedness score
covid_data = covid_data %>%
  select(m_turk_code, contains("gov_prep")) %>%
  gather(item, value, -m_turk_code) %>%
  group_by(m_turk_code) %>%
  summarize(gov_prep = mean(value)) %>%
  full_join(covid_data)

# make column for trust in gov score
covid_data = covid_data %>%
  select(m_turk_code, contains("trust_in_gov")) %>%
  gather(item, value, -m_turk_code) %>%
  group_by(m_turk_code) %>%
  summarize(trust = mean(value)) %>%
  full_join(covid_data)

# make column for gov performance score
covid_data = covid_data %>%
  select(m_turk_code, contains("gov_perf")) %>%
  gather(item, value, -m_turk_code) %>%
  group_by(m_turk_code) %>%
  summarize(gov_perf = mean(value)) %>%
  full_join(covid_data)

# make column for gov compliance score
covid_data = covid_data %>%
  select(m_turk_code, contains("gov_comp")) %>%
  gather(item, value, -m_turk_code) %>%
  group_by(m_turk_code) %>%
  summarize(gov_comp = mean(value)) %>%
  full_join(covid_data)

# make column for risk perception score
covid_data = covid_data %>%
  select(m_turk_code, contains("risk")) %>%
  gather(item, value, -m_turk_code) %>%
  group_by(m_turk_code) %>%
  summarize(risk = mean(value)) %>%
  full_join(covid_data)

# make column for depression score
covid_data = covid_data %>%
  select(m_turk_code, contains("depression")) %>%
  gather(item, value, -m_turk_code) %>%
  group_by(m_turk_code) %>%
  summarize(dep = mean(value)) %>%
  full_join(covid_data)

# make column for anxiety score
covid_data = covid_data %>%
  select(m_turk_code, contains("anxiety")) %>%
  gather(item, value, -m_turk_code) %>%
  group_by(m_turk_code) %>%
  summarize(anx = mean(value)) %>%
  full_join(covid_data)

#Note: there may be a more succinct way to udpate your covid_data df without needing to individually select(), gather(), group(), summarize(), and then full_join() it. Becuase of my own unfamiliarity with your approach using the gather() function, I didn't dig too far into condensing this for you. Also, there may not be a more efficient way to do it; I'm unsure.

# covid_data = covid_data %>%
#  mutate(
#    dep = case_when(
#      country_of_residence == "Mexico" ~ NA_real_,
#      TRUE ~ dep), 
#    risk = case_when(
#      country_of_residence == "China" ~ NA_real_,
#      TRUE ~ risk)
#    )

```

# data viz 1

```{r dataviz_1}
#	Visualize the relationship between trust in government and likelihood of compliance with government policies, introducing country as a third variable. I think this would work well as a line plot or scatterplot, with different countries in different colors.
viz_1 <- covid_data %>% 
ggplot(aes(trust, gov_comp)) +
  geom_smooth(aes(colour = country_of_residence),
              #Colour spelled ^ with the non-American variant; love to see it!
             size = 0.5) +
  facet_wrap(~country_of_residence) +
  theme_minimal() +
  scale_color_viridis_d() +
  xlab("Trust in government") +
  ylab("Compliance with government policies") +
  labs(title = "Greater trust in government differentially predicts higher compliance",
       colour = "Country")
#Changed legend title to be succinct
viz_1
```

# data viz 2
```{r dataviz_2}
# Visualize the distribution of adoption of preventive behaviors by country. I think this would work well as a ridgeline plot or boxplots. 
# viridis(n = 9)
#likely don't need this ^ line of code

viz_2 <- covid_data %>% 
  mutate(country_of_residence = fct_relevel(country_of_residence,  "Australia", "USA", "Argentina", "Saudi Arabia", "Mexico", "Egypt", "China", "Nigeria", "India")) %>%
  ggplot(aes(prevent, country_of_residence)) +
  ggridges::geom_density_ridges(aes(fill = country_of_residence),
                                bandwidth = 0.6,
                                alpha = 0.5,
                                scale = 1.5) +
  scale_fill_manual(values = c("#440154FF", "#472D7BFF", "#3B528BFF", "#2C728EFF", "#21908CFF", "#27AD81FF", "#5DC863FF", "#AADC32FF", "#FDE725FF")) +
  theme_minimal() +
  theme(legend.position = "none") +
  xlab("Number of preventive behaviors adopted") +
  ylab("") +
  labs(title = "Adoption of preventive behaviors by country")
viz_2

#really well done - every line of code looks to have value and contribute to an awesome viz. My only point of improvement wasn't super related to the viz - it was just extraneous code
```

# data viz 3
```{r dataviz_3}
# Visualize the overlap between each of the predictor variables (trust in gov/perception of gov preparedness/perception of gov performance/risk perception/perceived controllability). I think this would work well as a heatmap or correlogram.
data_for_cor <- covid_data %>% 
  dplyr::select(c(trust, gov_perf, gov_prep, risk, control))
cor <- as.matrix(cor(data_for_cor))

viz_3 <- heatmaply(cor, 
        colors = magma(n = 512, alpha = 1, begin = 1, end = 0),
        # changed the colour palette to align with a (potentially) more intuitive gradient and increased the n size to sample a large amount of colours such that small differences in correlations are detectable
        dendrogram = "none",
        grid_color = "white",
        margins = c(60,100,50,20),
        fontsize_col = 8,
        fontsize_row = 8, 
        labCol = colnames(cor),
        labRow = rownames(cor),
        xlab = "", 
        ylab = "",
        main = "Correlational heatmap of predictor variables",
        heatmap_layers = theme(axis.line=element_blank()))
viz_3

#really nice! A small suggestion for colour gradient changes, but that's it

# I could do this on an item level...
# You could! I'd say that your first heatmap tells the same story with less units to keep track of in a correlation matrix. 
data_for_cor_full <- covid_data %>%
  select(contains("perceived_control"),
         contains("risk_perception"),
         contains("trust_in_gov"),
         contains("gov_preparedness"),
         contains("gov_performance"))
cor_full <- as.matrix(cor(data_for_cor_full))

viz_3_full <- heatmaply(cor_full, 
        colors = viridis(n = 256, alpha = 1, begin = 1, end = 0),
        dendrogram = "none",
        grid_color = "white",
        margins = c(60,100,50,20),
        fontsize_col = 8,
        fontsize_row = 8, 
        labCol = colnames(cor_full),
        labRow = rownames(cor_full),
        xlab = "", 
        ylab = "",
        main = "Correlational heatmap of predictor variables",
        heatmap_layers = theme(axis.line=element_blank()))
viz_3_full

```


